### PR TITLE
Summarize the cereal and beverage totals

### PR DESCRIPTION
**Pull request by alexbate**
It is critical to this application not just to know how much has been
consumed since records began (arbitrarily 1000 records ago), we must
also be able to convert this into units that can be easily visualised by
the target audience.

A red brick is said to be between 2 and 3 kg, so we have taken the mean
value of 2.5kg.

### CODE REVIEW

**Comment by alexbate** [comment]
I believe the issues raised regarding PEP8 complaince have been rectified. The calculations divide the total nosh by the new nosh unit in question, it is a typical unit conversion procedure.

**Comment by danielchatfield** [comment]
Will merge at some point before christmas

**Comment by danielchatfield** [comment]
This needs to be rebased then i'll merge

**Comment by alexbate** [comment]
Done

**Pull request merged**
